Setting PHP version per site

diff --git a/bin/fn b/bin/fn
--- a/bin/fn
+++ b/bin/fn
@@ -670,6 +670,22 @@ fn_ls() {
 #     fi
 # }
 
+set_php_version() {
+    if [[ ! $1 =~ [7-9]\.[0-9]$ ]]; then
+        echo "Invalid PHP version for site: $1"
+        exit 1
+    fi
+
+    php_ver_short="${1/\./}"
+    if grep -q "ext[pP]rocessor lsphp${php_ver_short}" /etc/uny/openlitespeed/conf/httpd_config.conf; then
+        sed "s|lsphp[0-9][0-9]|lsphp${php_ver_short}|" -i /etc/uny/openlitespeed/conf/vhosts/"$domain"/vhconf.conf
+        systemctl reload uny-openlitespeed
+    else
+        echo "PHP version not in OpenLitespeed. Aborting..."
+        exit 1
+    fi
+}
+
 set_enable() {
     if ls /etc/uny/openresty/sites-enabled/*"$domain"* >/dev/null 2>/dev/null; then
         echo "Site $domain is already enabled."
@@ -706,9 +722,9 @@ fn_set() {
             set_alias "$@"
             set_success=1
             ;;
-        firewall | waf)
+        php)
             shift
-            set_firewall "$@"
+            set_php_version "$@"
             set_success=1
             ;;
         enable)
