PHP version per site

diff --git a/bin/fn b/bin/fn
--- a/bin/fn
+++ b/bin/fn
@@ -97,8 +97,26 @@ EOF
 
         if [[ $php_site_version == "" ]]; then
             php_site_version="$(yq .php_default_version /var/qyc/cnf.yaml)"
+        else
+            # Check if php version is correct
+            if echo "$php_site_version" | grep -qv "[7-9]\.[0-9]$"; then
+                echo "$php_site_version is not a valid PHP version. Aborting."
+                rm -rf /var/www/"$domain" /etc/uny/openresty/sites-available/"$domain"
+                exit 1
+            fi
         fi
         php_site_version_short="${php_site_version//\./}"
+
+        for phpv in $(yq -ot .php_versions /var/qyc/cnf.yaml); do
+            if [[ $php_site_version == "$phpv" ]]; then
+                already_installed=yes
+            fi
+        done
+        if [[ $already_installed != "yes" ]]; then
+            php_new_vers="$(yq -oc .php_versions /var/qyc/cnf.yaml),$php_site_version"
+            qyc cnf php "$php_new_vers"
+        fi
+        unset already_installed
 
         sed -e "s|HTDOCS|/var/www/${domain}/htdocs|g" -e "s|SHORTVER|$php_site_version_short|g" \
             /var/qyc/qycli/cnf/openlitespeed/"$site_type"-vhostconf-template.conf >/etc/uny/openlitespeed/conf/vhosts/"$domain"/vhconf.conf
@@ -291,11 +309,12 @@ wp_cf_page_cache_token_and_plugin_options() {
 }
 
 mk_wp() {
-    mk_common "$@"
-    shift
-
     while [[ "$#" -gt 0 ]]; do
         case "$1" in
+        php | phpv | php-version)
+            php_site_version="$2"
+            shift
+            ;;
         u | user | admin)
             wpadmin="$2"
             shift
@@ -319,6 +338,9 @@ mk_wp() {
         esac
         shift
     done
+
+    mk_common "$@"
+    shift
 
     echo "Installing WordPress..."
     wget -qrO /var/www/"$domain"/htdocs/latest.tar.gz https://wordpress.org/latest.tar.gz
