Multi-PHP

diff --git a/bin/fn b/bin/fn
--- a/bin/fn
+++ b/bin/fn
@@ -766,15 +766,25 @@ fn_clone() {
     fi
 }
 
-cnf_php_version() {
-    if [[ "$1" =~ (8.[0-2]|7.4) ]]; then
-        new_ver=$1
-        export new_ver
-    else
-        echo "No correct version number for PHP, should be 7.4, 8.0 or 8.1"
-        exit
+cnf_php_versions() {
+    invalid_versions="$(echo "$1" | tr "," "\n" | grep -v "[7-9]\.[0-9]")"
+    if [ "$invalid_versions" != "" ]; then
+        for ver in $invalid_versions; do
+            echo "$ver is not a valid PHP version."
+        done
+        echo "Aborting PHP config change due to invalid PHP version(s)."
+        exit 1
     fi
-    sed "s/^php_version: .*/php_version: $1/" -i /var/qyc/cnf.yaml
+    php_versions="$(echo "$1" | tr "," "\n")"
+
+    php_default_version="$(echo "$php_versions" | head -n1)"
+    yq ".php_default_version = $php_default_version" -i /var/qyc/cnf.yaml
+
+    yq 'del(.php_versions)' -i /var/qyc/cnf.yaml
+    for ver in $php_versions; do
+        yq ".php_versions += [$ver]" -i /var/qyc/cnf.yaml
+    done
+
     upd_php
 }
 
@@ -783,10 +793,7 @@ cnf_php_parser() {
         case "$1" in
         v | ver | version)
             shift
-            cnf_php_version "$@"
-            ;;
-        8.1 | 8.0 | 7.4 | 8.2)
-            cnf_php_version "$@"
+            cnf_php_versions "$@"
             ;;
         *)
             echo "Invalid option: $1"
diff --git a/ins/inst-parser b/ins/inst-parser
--- a/ins/inst-parser
+++ b/ins/inst-parser
@@ -5,7 +5,7 @@
 
 sec_install=no
 kernel_tweaks=yes
-php_version=8.2
+php_versions=8.3
 auto_update=no
 
 while [ "$#" -gt 0 ]; do
@@ -22,8 +22,18 @@ while [ "$#" -gt 0 ]; do
         fi
         shift
         ;;
-    php | phpv | php-version)
-        php_version=$2
+    php | phpv | php-versions)
+        php_versions=$2
+        invalid_versions="$(echo "$php_versions" | tr "," "\n" | grep -v "[7-9]\.[0-9]")"
+        if [ "$invalid_versions" != "" ]; then
+            for ver in $invalid_versions; do
+                echo "$ver is not a valid PHP version."
+            done
+            echo "Aborting installation due to invalid PHP version(s)."
+            exit 1
+        fi
+        php_versions="$(echo "$php_versions" | tr "," "\n")"
+        php_default_version="$(echo "$php_versions" | head -n1)"
         shift
         ;;
     cft | cloudflare-token)
