changing crowdsec token handling

diff --git a/bin/fn b/bin/fn
--- a/bin/fn
+++ b/bin/fn
@@ -47,16 +47,33 @@ FLUSH PRIVILEGES;
 EOF
 }
 
-mk_site_create_cf_api_token_crowdsec_and_dns() {
+mk_site_create_cf_api_token_crowdsec() {
+    root_domain_account_id=$(yq '.[].[] | select(.name == "'"$root_domain"'").account.id' /var/opt/qycli/cloudflare/cfzones.json)
+    if [[ $root_domain_account_id != "" ]]; then
+        if [[ ! -f /var/opt/qycli/cloudflare/crowdsec/cf_token_crowdsec_"$root_domain_account_id".json ]]; then
+            # Create CrowdSec and DNS Token
+            curl -X POST "https://api.cloudflare.com/client/v4/user/tokens" \
+                -H "Authorization: Bearer $cf_token" \
+                -H "Content-Type: application/json" \
+                --data '{"name":"qycli CrowdSec - '"$root_domain_account_id"'","policies":[{"effect":"allow","resources":{"com.cloudflare.api.account.'"$root_domain_account_id"'":"*"},"permission_groups":[{"id":"2edbf20661fd4661b0fe10e9e12f485c","name":"Account Rule Lists Write"},{"id":"a416acf9ef5a4af19fb11ed3b96b1fe6","name":"Account Firewall Access Rules Write"}]},{"effect":"allow","resources":{"com.cloudflare.api.account.zone.*":"*"},"permission_groups":[{"id":"c8fed203ed3043cba015a93ad1616f1f","name":"Zone Read"},{"id": "fb6778dc191143babbfaa57993f1d275","name": "Zone WAF Write"},{"id": "43137f8d07884d3198dc0ee77ca6e79b","name": "Firewall Services Write"}]}]}' >/var/opt/qycli/cloudflare/crowdsec/cf_token_crowdsec_"$root_domain_account_id".json
+        fi
+    else
+        echo "Account ID for the root domain $root_domain cannot be found in /var/opt/qycli/cloudflare/cfzones.json,"
+        echo "because the file either doesn't exist or the Cloudflare API token is not linked to"
+        echo "the Account with the right Zone/Domain."
+    fi
+}
+
+mk_site_create_cf_api_token_dns() {
     root_domain_zone_id=$(yq '.[].[] | select(.name == "'"$root_domain"'").id' /var/opt/qycli/cloudflare/cfzones.json)
     if [[ $root_domain_zone_id != "" ]]; then
-        if [[ ! -f /var/opt/qycli/cloudflare/"$root_domain"/cf_token_crowdsec_and_dns.json ]]; then
+        if [[ ! -f /var/opt/qycli/cloudflare/dns/"$root_domain"/cf_token_dns.json ]]; then
             root_domain_account_id=$(yq '.[].[] | select(.name == "'"$root_domain"'").account.id' /var/opt/qycli/cloudflare/cfzones.json)
             # Create CrowdSec and DNS Token
             curl -X POST "https://api.cloudflare.com/client/v4/user/tokens" \
                 -H "Authorization: Bearer $cf_token" \
                 -H "Content-Type: application/json" \
-                --data '{"name":"'"$root_domain"' qycli CrowdSec + DNS","policies":[{"effect":"allow","resources":{"com.cloudflare.api.account.'"$root_domain_account_id"'":"*"},"permission_groups":[{"id":"2edbf20661fd4661b0fe10e9e12f485c","name":"Account Rule Lists Write"},{"id":"a416acf9ef5a4af19fb11ed3b96b1fe6","name":"Account Firewall Access Rules Write"}]},{"effect":"allow","resources":{"com.cloudflare.api.account.zone.'"$root_domain_zone_id"'":"*"},"permission_groups":[{"id":"3030687196b94b638145a3953da2b699","name":"Zone Settings Write"},{"id":"c8fed203ed3043cba015a93ad1616f1f","name":"Zone Read"},{"id": "4755a26eedb94da69e1066d98aa820be","name":"DNS Write"},{"id": "fb6778dc191143babbfaa57993f1d275","name": "Zone WAF Write"},{"id": "43137f8d07884d3198dc0ee77ca6e79b","name": "Firewall Services Write"}]}]}' >/var/opt/qycli/cloudflare/"$root_domain"/cf_token_crowdsec_and_dns.json
+                --data '{"name":"'"$root_domain"' qycli CrowdSec + DNS","policies":[{"effect":"allow","resources":{"com.cloudflare.api.account.'"$root_domain_account_id"'":"*"},"permission_groups":[{"id":"2edbf20661fd4661b0fe10e9e12f485c","name":"Account Rule Lists Write"},{"id":"a416acf9ef5a4af19fb11ed3b96b1fe6","name":"Account Firewall Access Rules Write"}]},{"effect":"allow","resources":{"com.cloudflare.api.account.zone.'"$root_domain_zone_id"'":"*"},"permission_groups":[{"id":"3030687196b94b638145a3953da2b699","name":"Zone Settings Write"},{"id":"c8fed203ed3043cba015a93ad1616f1f","name":"Zone Read"},{"id": "4755a26eedb94da69e1066d98aa820be","name":"DNS Write"}]}]}' >/var/opt/qycli/cloudflare/dns/"$root_domain"/cf_token_dns.json
         fi
     else
         echo "Root domain $root_domain cannot be found in /var/opt/qycli/cloudflare/cfzones.json,"
@@ -67,15 +84,20 @@ mk_site_create_cf_api_token_crowdsec_and_dns() {
 
 mk_site_cnf_crowdsec_cloudflare_bouncer() {
     separator=''
-    cf_crowdsec_tokens=$(for json in /var/opt/qycli/cloudflare/*/cf_token_crowdsec_and_dns.json; do
+    cf_crowdsec_tokens=$(for json in /var/opt/qycli/cloudflare/crowdsec/cf_token_crowdsec_*.json; do
         echo -n "$separator""$(yq .result.value "$json")"
         separator=','
     done)
 
-    crowdsec-cloudflare-bouncer -d
-    crowdsec-cloudflare-bouncer -g "$cf_crowdsec_tokens" -o /etc/crowdsec/bouncers/crowdsec-cloudflare-bouncer.yaml
-    crowdsec-cloudflare-bouncer -s
-    systemctl restart crowdsec-cloudflare-bouncer
+    new_cf_crowdsec_tokens_sorted=$(echo "$cf_crowdsec_tokens" | tr ',' '\n' | sort)
+    old_cf_crowdsec_tokens_sorted=$(yq .cloudflare_config.accounts.[].token /etc/crowdsec/bouncers/crowdsec-cloudflare-bouncer.yaml | sort)
+
+    if ! test "$new_cf_crowdsec_tokens_sorted" = "$old_cf_crowdsec_tokens_sorted"; then
+        crowdsec-cloudflare-bouncer -d
+        crowdsec-cloudflare-bouncer -g "$cf_crowdsec_tokens" -o /etc/crowdsec/bouncers/crowdsec-cloudflare-bouncer.yaml
+        crowdsec-cloudflare-bouncer -s
+        systemctl restart crowdsec-cloudflare-bouncer
+    fi
 }
 
 mk_site() {
@@ -106,7 +128,8 @@ EOF
 
     cf_token=$(yq .cloudflare_token /var/opt/qycli/cnf.yaml)
     if [[ $cf_token != "" ]]; then
-        mk_site_create_cf_api_token_crowdsec_and_dns
+        mk_site_create_cf_api_token_dns
+        mk_site_create_cf_api_token_crowdsec
         mk_site_cnf_crowdsec_cloudflare_bouncer
     fi
 }
