Multi-PHP

diff --git a/bin/upd b/bin/upd
--- a/bin/upd
+++ b/bin/upd
@@ -18,6 +18,25 @@ upd_get_ram_mb() {
 
 upd_openlitespeed_conf() {
     sed -zEn "/(address.*\*)/{s/\*/[::1]/;p}" -i /etc/uny/openlitespeed/conf/httpd_config.conf
+
+    for phpv in $(yq -ot .php_versions /var/qyc/cnf.yaml); do
+        phpv_short="${phpv//\./}"
+
+        lsphp_path=(/uny/pkg/php/"$phpv"*/bin/lsphp*)
+        if echo "${lsphp_path[0]}" | grep -q "\*"; then
+            echo "PHP $phpv installation directory does not exist. Aborting."
+            return 1
+        fi
+
+        if ! grep -q "extprocessor lsphp${phpv_short}" /etc/uny/openlitespeed/conf/httpd_config.conf; then
+            ols_extproc="$(
+                sed -e "s|SHORTVER|$phpv_short|g" -e "s|LSPHP_PATH|${lsphp_path[0]}|g" \
+                    /var/qyc/qycli/cnf/openlitespeed/extprocessor-template.conf
+            )"
+            sed -zEn "s|(extprocessor lsphp.*\{[^\}]*})|&\n\n${ols_extproc}|p" -i /etc/uny/openlitespeed/conf/httpd_config.conf
+        fi
+    done
+
     systemctl restart uny-openlitespeed
 }
 
@@ -353,10 +372,10 @@ upd_fn() {
     upd_mariadb_conf
     upd_openresty
     upd_openresty_conf
-    upd_openlitespeed
-    upd_openlitespeed_conf
     upd_php
     upd_php_conf
+    upd_openlitespeed
+    upd_openlitespeed_conf
     upd_valkey_conf
     upd_valkey_service
     upd_psl
