Print installation info

diff --git a/bin/upd b/bin/upd
--- a/bin/upd
+++ b/bin/upd
@@ -204,9 +204,26 @@ upd_get_cf_accounts_and_zones() {
 
 upd_get_cf_tokens() {
     cf_token=$(yq .cloudflare_token /var/qyc/cnf.yaml)
-    time="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
+    cf_token_accounts_zones_dns=$(yq -oc .result.value /var/qyc/cloudflare/cf_token_accounts_zones_dns.json)
+
+    cf_token_accounts_zones_dns_verify_answer="$(curl -s -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
+        -H "Authorization: Bearer $cf_token_accounts_zones_dns" \
+        -H "Content-Type: application/json")"
+    if [[ $(yq .success <<<"$cf_token_accounts_zones_dns_verify_answer") == "true" && $(yq .result.status <<<"$cf_token_accounts_zones_dns_verify_answer") == "active" ]]; then
+        cf_token_accounts_zones_dns_id="$(yq .result.id <<<"$cf_token_accounts_zones_dns_verify_answer")"
+        # Restore API result for /var/qyc/cloudflare/cf_token_accounts_zones_dns.json with yq ".result.value = 'CFTTOKEN'"
+        curl -X GET https://api.cloudflare.com/client/v4/user/tokens/"$cf_token_accounts_zones_dns_id" \
+            -H "Authorization: Bearer $cf_token" \
+            -H "Content-Type: application/json" \
+            >/var/qyc/cloudflare/cf_token_accounts_zones_dns.json
+        yq ".result.value = 'CFTTOKEN'" -i /var/qyc/cloudflare/cf_token_accounts_zones_dns.json
+    else
+        echo "Cloudflare token for accounts, zones and DNS cannot be verified. Aborting."
+        exit 1
+    fi
 
     if [[ $cf_token != "" ]]; then
+        time="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
         # Create Accounts Zones and DNS Token
         curl -X POST "https://api.cloudflare.com/client/v4/user/tokens" \
             -H "Authorization: Bearer $cf_token" \
