Update inst

diff --git a/ins/inst b/ins/inst
--- a/ins/inst
+++ b/ins/inst
@@ -3,12 +3,13 @@
 
 ## Install qycli dev version and stack with "wget -qO- qyc.li/i/stable | bash -s cft YOURTOKENHERE" or the dev version with "wget -qO- qyc.li/i/dev | bash -s cft YOURTOKENHERE"
 ## or "bash <(wget -qO- qyc.li/inst) v dev k no phpv 7.4"
+## To install without Cloudflare token do the following: wget -qO- qyc.li/i/stable | bash -s no-cft
 
 [ "$(whoami)" != "root" ] && echo "qycli has to be installed as root, try 'sudo -i' or 'su -' to become root, then try again." && exit
 [ -f /bin/qyc ] && echo "qycli is already installed, stopping. Just type qyc to get the help message or go to qycli.org to learn." && exit
 
 kernel_tweaks=yes
-php_versions=8.3
+php_versions=8.4
 auto_update=no
 
 while [ "$#" -gt 0 ]; do
@@ -29,6 +30,10 @@ while [ "$#" -gt 0 ]; do
         fi
         php_versions="$(echo "$php_versions" | tr "," "\n")"
         php_default_version="$(echo "$php_versions" | head -n1)"
+        shift
+        ;;
+    no-cft | no-cloudflare-token)
+        no_cloudflare_token=true
         shift
         ;;
     cft | cloudflare-token)
@@ -54,22 +59,24 @@ done
 echo "Installing qycli."
 echo
 
-if [ "$cloudflare_token" = "" ]; then
+if [ "$no_cloudflare_token" != "true" ] && [ "$cloudflare_token" = "" ]; then
     echo "You need to supply a Clouflare User API token (Not an Account Token) with the permission template 'Create Additional Tokens'."
     echo "Then you supply it to the qycli installation like this: wget -qO- qyc.li/i/stable | bash -s cft YOURTOKENHERE"
     echo "qycli only works with Cloudflare. Aborting."
     exit 1
-fi
+elif [ "$no_cloudflare_token" != "true" ] && [ "$cloudflare_token" != "" ]; then
 
-if wget --method=get -O- -q \
-    --header="Authorization: Bearer $cloudflare_token" \
-    --header="Content-Type:application/json" \
-    https://api.cloudflare.com/client/v4/user/tokens/verify >/dev/null; then
+    if wget --method=get -O- -q \
+        --header="Authorization: Bearer $cloudflare_token" \
+        --header="Content-Type:application/json" \
+        https://api.cloudflare.com/client/v4/user/tokens/verify >/dev/null; then
 
-    echo "Cloudflare User Token verified."
-else
-    echo "Needs to be a Cloudflare User Token not an Account Token. Aborting."
-    exit 1
+        echo "Cloudflare User Token verified."
+    else
+        echo "Needs to be a Cloudflare User Token not an Account Token. Aborting."
+        exit 1
+    fi
+
 fi
 
 if [ ! -d /var/qyc ]; then
@@ -127,9 +134,11 @@ printf "\nqycli (%s) script was installed.\n\n" "$branch_name"
 printf "\nInstalling the qycli stack now through unypkg.\n\n"
 stk_install
 
-printf "\nGetting Cloudflare data.\n\n"
-upd_get_cf_tokens
-upd_get_cf_accounts_and_zones
+if [ "$no_cloudflare_token" != "true" ]; then
+    printf "\nGetting Cloudflare data.\n\n"
+    upd_get_cf_tokens
+    upd_get_cf_accounts_and_zones
+fi
 
 if ! systemd-detect-virt --container --quiet && [ "$kernel_tweaks" = "yes" ]; then
     printf "\nOptimizing kernel configurations. You should restart after the full installation has finished.\n\n"
